import { createFileRoute, Link, notFound, redirect } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { SiteLayout } from "@/components/site-layout";
import { PageHero } from "@/components/page-hero";
import { TechnicalRoadmapCTA } from "@/components/technical-roadmap-cta";
import { SystemsWeIntegrate } from "@/components/systems-we-integrate";
import { allServices, industries } from "@/lib/site-data";
import { getCmsContentItem, getCmsContentList } from "@/lib/logicsify-api";
import { PublicRouteLoading } from "@/components/public-route-loading";

const details: Record<string,{problems:string[];systems:string[];opportunities:string[];services:string[];model:string;faqs:Array<{q:string;a:string}>}>={
  "saas-startups":{problems:["Turning a validated idea into a scoped MVP","Designing multi-tenant data, permissions, and billing","Improving onboarding and activation","Building admin and reporting systems before scale creates operational debt"],systems:["Supabase or PostgreSQL","Stripe","Product analytics","Customer support","Email and lifecycle tools"],opportunities:["Lead and product-qualified account routing","Onboarding reminders and activation workflows","Subscription and entitlement operations","Internal reporting and customer health alerts"],services:["saas-development","ui-ux","web-applications","ai-automations","api-integrations","cro"],model:"Fixed-scope discovery and MVP phases, followed by monthly product support or a dedicated team when the roadmap becomes continuous.",faqs:[{q:"Can Logicsify build only the MVP?",a:"Yes, when the MVP has a defined validation goal and a realistic release boundary. Discovery should separate validation features from later platform work."},{q:"Can AI features be added later?",a:"Usually. The data model and permissions should still anticipate how model access, evaluation, and user consent will work."}]},
  "home-services":{problems:["Slow response to calls and forms","Leads falling between marketing, office staff, and technicians","Inconsistent booking and follow-up","Difficulty connecting booked jobs back to advertising spend"],systems:["GoHighLevel or HubSpot","Call tracking and telephony","Calendar and dispatch systems","Google Ads and Meta","Review and messaging tools"],opportunities:["Missed-call follow-up","Lead qualification and routing","Appointment reminders","Review requests","Pipeline and booked-job reporting"],services:["crm-automation","ai-agents","paid-advertising","seo","api-integrations","web-design-development"],model:"Start with automation consulting or a focused fixed-scope workflow, then use monthly support for campaign, CRM, and operational improvement.",faqs:[{q:"Can the system book jobs automatically?",a:"Only when availability, service area, job type, and handoff rules are explicit. High-risk or unclear requests should remain human-confirmed."},{q:"Can advertising reports show booked jobs?",a:"Yes when call, form, CRM, and job status data can be connected with reliable identifiers and permissions."}]},
  healthcare:{problems:["Manual intake and document handling","Appointment and reminder gaps","Disconnected staff workflows","Accessibility and data-handling requirements that generic tools do not fit"],systems:["Scheduling and intake platforms","Secure document storage","Staff portals","Reporting systems","Email and messaging providers"],opportunities:["Intake validation and routing","Appointment reminders","Document review queues","Staff task notifications","Operational reporting"],services:["web-applications","ui-ux","api-integrations","ai-automations","web-design-development"],model:"Use paid discovery before implementation. Data handling, vendors, permissions, and contractual obligations must be verified before any compliance claim.",faqs:[{q:"Does Logicsify guarantee HIPAA compliance?",a:"No. Compliance depends on the full system, vendors, contracts, policies, access controls, and operating practices. Those requirements must be verified during discovery."},{q:"Can patient or client intake be automated?",a:"Parts can be automated when validation, consent, retention, access, and escalation rules are clearly defined."}]},
  ecommerce:{problems:["Slow mobile storefront performance","Disconnected product, inventory, CRM, and support data","Checkout friction","Lifecycle campaigns that do not reflect customer behavior"],systems:["Shopify","Stripe or platform payments","Inventory and fulfillment systems","CRM and email platforms","Google Ads and Meta"],opportunities:["Product and inventory synchronization","Abandoned checkout and post-purchase flows","Customer support routing","Lifecycle segmentation","Marketing-to-revenue reporting"],services:["ecommerce","cro","api-integrations","content-marketing","paid-advertising","ai-automations"],model:"A fixed-scope storefront or integration project works for defined launches. Monthly support fits merchandising, experimentation, and lifecycle improvement.",faqs:[{q:"Do you only work with Shopify?",a:"No. Shopify is often appropriate, but headless or custom commerce should be justified by product, content, workflow, or integration constraints."},{q:"Can you improve checkout conversion?",a:"We can identify and test friction, but no conversion lift should be promised before reviewing traffic quality, analytics, device mix, and the current funnel."}]},
  agencies:{problems:["Overflow work that changes month to month","Inconsistent handoff between design and development","Client sites that are difficult to maintain","Reporting and delivery work repeated across accounts"],systems:["Project management","Custom CMS platforms","CRM and client portals","Reporting dashboards","Automation platforms"],opportunities:["Reusable client onboarding","White-label status reporting","Content and deployment workflows","Lead and opportunity routing","Repeatable QA checklists"],services:["web-design-development","web-applications","ui-ux","api-integrations","crm-automation","maintenance"],model:"Monthly development support or a dedicated team usually fits repeatable agency delivery. Fixed-scope work is better for isolated client projects.",faqs:[{q:"Can Logicsify work white-label?",a:"Yes, when communication ownership, review process, access, and client-facing responsibilities are agreed in writing."},{q:"Can you use our design system and process?",a:"Yes. The onboarding phase should define repositories, components, QA rules, project management, and handoff expectations."}]},
};

export const Route=createFileRoute("/industries/$slug")({pendingComponent:PublicRouteLoading,loader:async({params})=>{if(params.slug==="startups-saas")throw redirect({to:"/industries/$slug",params:{slug:"saas-startups"},replace:true});const fallback=industries.find((item)=>item.slug===params.slug);const config=details[params.slug];if(!fallback||!config)throw notFound();const[cms,cases]=await Promise.all([getCmsContentItem("industry",params.slug),getCmsContentList("case_study")]);return{industry:{...fallback,name:cms?.title||fallback.name,desc:cms?.excerpt||fallback.desc,body:String(cms?.content_json?.body||"")},config,relatedCases:cases.filter((item)=>String(item.content_json?.industry||item.content_json?.category||"").toLowerCase().includes(fallback.name.split(" ")[0].toLowerCase())).slice(0,3)}} ,component:IndustryPage,head:({loaderData,params})=>({meta:[{title:`${loaderData?.industry.name||"Industry"} Technology & Automation | Logicsify`},{name:"description",content:loaderData?.industry.desc||""},{property:"og:title",content:`${loaderData?.industry.name||"Industry"} | Logicsify`},{property:"og:description",content:loaderData?.industry.desc||""},{property:"og:url",content:`https://logicsify.com/industries/${params.slug}`}],links:[{rel:"canonical",href:`https://logicsify.com/industries/${params.slug}`} ]})});

function IndustryPage(){const{industry,config,relatedCases}=Route.useLoaderData();const relevant=allServices.filter((item)=>config.services.includes(item.slug));return <SiteLayout>
  <PageHero eyebrow={industry.tag} breadcrumbs={[{label:"Home",to:"/"},{label:"Industries",to:"/industries"},{label:industry.name}]} title={<>{industry.name} systems built around <span className="text-gradient">real operating constraints.</span></>} intro={industry.desc} primaryCta={{label:"Get a Free Technical Roadmap",to:"/technical-roadmap"}} secondaryCta={{label:"See relevant work",to:"/work"}} />
  <section className="py-20"><div className="container-page grid gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><p className="eyebrow mb-4">Industry-specific problems</p><h2 className="fluid-h2">Where generic systems usually break.</h2></div><ul className="space-y-4 lg:col-span-7">{config.problems.map((item)=><li key={item} className="flex gap-3 text-lg text-ink-soft"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-brand-red"/>{item}</li>)}</ul></div></section>
  <section className="bg-cream py-20"><div className="container-page"><p className="eyebrow mb-4">Relevant services</p><h2 className="fluid-h2">Where we typically start.</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{relevant.map((service)=><Link key={service.slug} to={service.route} className="rounded-2xl bg-white p-6"><h3 className="text-lg font-semibold">{service.name}</h3><p className="mt-2 text-sm text-ink-soft">{service.short}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-semibold">Explore <ArrowRight className="h-4 w-4"/></span></Link>)}</div></div></section>
  <section className="py-20"><div className="container-page grid gap-6 lg:grid-cols-2"><Card title="Common systems" items={config.systems}/><Card title="Automation opportunities" items={config.opportunities}/></div></section>
  <section className="bg-ink py-20 text-white"><div className="container-page grid gap-8 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow text-white/60">Recommended engagement model</p><h2 className="mt-4 fluid-h3">Match delivery to uncertainty.</h2></div><div className="lg:col-span-8"><p className="text-xl leading-relaxed text-white/70">{config.model}</p><Link to="/engagement-models" className="btn-ghost-dark mt-6">Compare engagement models</Link></div></div></section>
  <SystemsWeIntegrate />
  {relatedCases.length?<section className="py-20"><div className="container-page"><h2 className="fluid-h3">Relevant case studies</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{relatedCases.map((item)=><Link key={item.id} to="/work/$slug" params={{slug:item.slug}} className="rounded-2xl border border-black/10 p-6"><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm text-ink-soft">{item.excerpt}</p></Link>)}</div></div></section>:null}
  <section className="bg-cream py-20"><div className="container-page"><p className="eyebrow mb-4">Process</p><h2 className="fluid-h3">A controlled path from discovery to support.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["Discovery","Scope and technical plan","Design and implementation","QA, launch, and iteration"].map((item,index)=><div key={item} className="rounded-2xl bg-white p-6"><span className="eyebrow">{String(index+1).padStart(2,"0")}</span><h3 className="mt-3 font-semibold">{item}</h3></div>)}</div></div></section>
  <section className="py-20"><div className="container-page max-w-4xl"><h2 className="fluid-h3">Frequently asked questions</h2><div className="mt-8 divide-y divide-black/10 rounded-2xl border border-black/10">{config.faqs.map((faq)=><details key={faq.q} className="group p-5"><summary className="cursor-pointer list-none font-semibold">{faq.q}</summary><p className="mt-3 text-ink-soft">{faq.a}</p></details>)}</div>{industry.body?<div className="public-prose mt-10" dangerouslySetInnerHTML={{__html:industry.body}}/>:null}</div></section>
  <TechnicalRoadmapCTA source={`industry:${industry.slug}`} />
</SiteLayout>}
function Card({title,items}:{title:string;items:string[]}){return <div className="rounded-3xl border border-black/10 p-8"><h2 className="fluid-h3">{title}</h2><ul className="mt-6 space-y-3">{items.map((item)=><li key={item} className="flex gap-3 text-ink-soft"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-brand-red"/>{item}</li>)}</ul></div>}
